FROM ${DOCKER_ORG_NAME}/${PKG_NAME}-srpm-deps

MAINTAINER "Jiao Lin <jiao.lin@gmail.com>"

# RUN yum install -y deltarpm
# RUN yum install -y git cmake make gcc-c++ python python-devel rpm-build
# RUN rpmbuild --rebuild https://github.com/danse-inelastic/danse.ins/releases/download/v1.0/danse.ins-1.0-0.src.rpm
RUN rpmbuild --rebuild ${GITHUB_URL}/releases/download/v${VERSION}/${PKG_NAME}-${VERSION}-${CPACK_PACKAGE_RELEASE}.src.rpm
RUN rpm -i ~/rpmbuild/RPMS/x86_64/${PKG_NAME}-${VERSION}-${CPACK_PACKAGE_RELEASE}.x86_64.rpm
